---
title: "Cancer Projections Prep"
format: html
editor: visual
---

## Packages

```{r}
library(readxl)
library(dplyr)

```

## Data

```{r}
setwd("C:/Users/rfrost/OneDrive - The Institute of Cancer Research/Documents/UK-cancer-trends/Data/Cancer Trends/Globocan")

data <- read_excel("Cancer_Projection_Data.xlsx")

inc_data <- data |>
  filter(Type == 0) |>
  select(Year, Sex, `ASR (World)`, `Cancer label`) |>
  arrange(`Cancer label`, Sex, Year)

write.csv(inc_data, "Cancer_Incidence_Data.txt", row.names = F)

mort_data <- data |>
  filter(Type == 1) |>
  select(Year, Sex, `ASR (World)`, `Cancer label`) |>
  arrange(`Cancer label`, Sex, Year)

write.csv(mort_data, "Cancer_Mortality_Data.txt", row.names = F)

```

## All Cancer Data

```{r}

setwd("C:/Users/rfrost/OneDrive - The Institute of Cancer Research/Documents/UK-cancer-trends/Data/Cancer Trends/Globocan All")

data <- read_excel("Cancer_Projection_Data_All.xlsx")

inc_data <- data |>
  filter(Type == 0) |>
  select(Year, Sex, `ASR (World)`, `Cancer label`) |>
  arrange(`Cancer label`, Sex, Year)

write.csv(inc_data, "Cancer_Incidence_Data_All.txt", row.names = F)

mort_data <- data |>
  filter(Type == 1) |>
  select(Year, Sex, `ASR (World)`, `Cancer label`) |>
  arrange(`Cancer label`, Sex, Year)

write.csv(mort_data, "Cancer_Mortality_Data_All.txt", row.names = F)


```

## Colorectal Cancer

```{r}
setwd("C:/Users/rfrost/OneDrive - The Institute of Cancer Research/Documents/UK-cancer-trends/Data/Cancer Trends/Globocan Colorectal")

data_young <- read_excel("Cancer_Projection_Data_Colorectal.xlsx", sheet = "UK_0_59") |>
  mutate(age_group = "0-59")


data_old <- read_excel("Cancer_Projection_Data_Colorectal.xlsx", sheet = "UK_60_85") |>
  mutate(age_group = "60-85")

data_inc <- rbind(data_young, data_old) |>
  filter(Type == 0) |>
  select(Year, Sex, `ASR (World)`, `Cancer label`, age_group) |>
  arrange(age_group, `Cancer label`, Sex, Year)


data_mort <- rbind(data_young, data_old) |>
  filter(Type == 1) |>
  select(Year, Sex, `ASR (World)`, `Cancer label`, age_group) |>
  arrange(age_group, `Cancer label`, Sex, Year)


write.csv(data_inc, "Cancer_Incidence_Data_Colorectal.txt", row.names = F)
write.csv(data_mort, "Cancer_Mortality_Data_Colorectal.txt", row.names = F)

```

## Extra Data

```{r}
setwd("C:/Users/rfrost/OneDrive - The Institute of Cancer Research/Documents/UK-cancer-trends/Data/Cancer Trends/Globocan Extra")

data <- read_excel("Cancer_Projection_Data_Extra.xlsx")

inc_data <- data |>
  filter(Type == 0) |>
  select(Year, Sex, `ASR (World)`, `Cancer label`) |>
  arrange(`Cancer label`, Sex, Year)

write.csv(inc_data, "Cancer_Incidence_Data_Extra.txt", row.names = F)

mort_data <- data |>
  filter(Type == 1) |>
  select(Year, Sex, `ASR (World)`, `Cancer label`) |>
  arrange(`Cancer label`, Sex, Year)

write.csv(mort_data, "Cancer_Mortality_Data_Extra.txt", row.names = F)

```

## Split by Country

```{r}
setwd("C:/Users/rfrost/OneDrive - The Institute of Cancer Research/Documents/UK-cancer-trends/Data/Cancer Trends/Globocan By Country")

data_england_wales <- read_excel("Cancer_Projection_Data_England_Wales.xlsx")

data_england_wales <- data_england_wales |>
  mutate(incmort = case_when(
    Type == 0 ~ "Incidence",
    Type == 1 ~ "Mortality",
    TRUE ~ NA),
    
    `Country label` = gsub(`Country label`, pattern = "UK, ", replacement = "")) |>
  
  select(Year, Sex, `ASR (World)`, `Cancer label`, incmort) |>
  
  arrange(Sex, `Cancer label`, incmort, Year, `ASR (World)`)
  
write.csv(data_england_wales, "England Wales/Cancer_Data_England_Wales.txt", row.names = F)

data_scotland <- read_excel("Cancer_Projection_Data_Scotland.xlsx")

data_scotland <- data_scotland |>
  mutate(incmort = case_when(
    Type == 0 ~ "Incidence",
    Type == 1 ~ "Mortality",
    TRUE ~ NA),
    
    `Country label` = gsub(`Country label`, pattern = "UK, ", replacement = "")) |>
  
  select(Year, Sex, `ASR (World)`, `Cancer label`, incmort) |>
  
  arrange(Sex, `Cancer label`, incmort, Year, `ASR (World)`)
  
write.csv(data_scotland, "Scotland/Cancer_Data_Scotland.txt", row.names = F)

data_nireland <- read_excel("Cancer_Projection_Data_NIreland.xlsx")

data_nireland <- data_nireland |>
  mutate(incmort = case_when(
    Type == 0 ~ "Incidence",
    Type == 1 ~ "Mortality",
    TRUE ~ NA),
    
    `Country label` = gsub(`Country label`, pattern = "UK, ", replacement = "")) |>
  
  select(Year, Sex, `ASR (World)`, `Cancer label`, incmort) |>
  
  arrange(Sex, `Cancer label`, incmort, Year, `ASR (World)`)
  
write.csv(data_nireland, "N Ireland/Cancer_Data_NIreland.txt", row.names = F)
```

## Data - by Country last 20 years
```{r}
setwd("C:/Users/rfrost/OneDrive - The Institute of Cancer Research/Documents/UK-cancer-trends/Data/Cancer Trends/Globocan By Country Last 20")

data_england_wales <- read_excel("Cancer_Projection_Data_England_Wales.xlsx")

max_inc <- max(data_england_wales$Year[data_england_wales$Type == 0])
max_mort <- max(data_england_wales$Year[data_england_wales$Type == 1])

data_england_wales <- data_england_wales |>
  mutate(incmort = case_when(
    Type == 0 ~ "Incidence",
    Type == 1 ~ "Mortality",
    TRUE ~ NA),

    `Country label` = gsub(`Country label`, pattern = "UK, ", replacement = "")) |>

  select(Year, Sex, `ASR (World)`, `Cancer label`, incmort) |>

  filter(case_when(
    incmort == "Incidence" ~ Year >= max_inc - 20,
    incmort == "Mortality" ~ Year >= max_mort - 20
  )) |>

  arrange(Sex, `Cancer label`, incmort, Year, `ASR (World)`)

write.csv(data_england_wales, "England Wales/Cancer_Data_England_Wales_Last_20.txt", row.names = F)

data_scotland <- read_excel("Cancer_Projection_Data_Scotland.xlsx")

max_inc <- max(data_scotland$Year[data_scotland$Type == 0])
max_mort <- max(data_scotland$Year[data_scotland$Type == 1])

data_scotland <- data_scotland |>
  mutate(incmort = case_when(
    Type == 0 ~ "Incidence",
    Type == 1 ~ "Mortality",
    TRUE ~ NA),
    
    `Country label` = gsub(`Country label`, pattern = "UK, ", replacement = "")) |>
  
  select(Year, Sex, `ASR (World)`, `Cancer label`, incmort) |>
  
  filter(case_when(
    incmort == "Incidence" ~ Year >= max_inc - 20,
    incmort == "Mortality" ~ Year >= max_mort - 20
  )) |>
  
  arrange(Sex, `Cancer label`, incmort, Year, `ASR (World)`)
  
write.csv(data_scotland, "Scotland/Cancer_Data_Scotland_Last_20.txt", row.names = F)

data_nireland <- read_excel("Cancer_Projection_Data_NIreland.xlsx")

max_inc <- max(data_nireland$Year[data_nireland$Type == 0])
max_mort <- max(data_nireland$Year[data_nireland$Type == 1])

data_nireland <- data_nireland |>
  mutate(incmort = case_when(
    Type == 0 ~ "Incidence",
    Type == 1 ~ "Mortality",
    TRUE ~ NA),
    
    `Country label` = gsub(`Country label`, pattern = "UK, ", replacement = "")) |>
  
  select(Year, Sex, `ASR (World)`, `Cancer label`, incmort) |>
  
  filter(case_when(
    incmort == "Incidence" ~ Year >= max_inc - 20,
    incmort == "Mortality" ~ Year >= max_mort - 20
  )) |>
  
  arrange(Sex, `Cancer label`, incmort, Year, `ASR (World)`)
  
write.csv(data_nireland, "N Ireland/Cancer_Data_NIreland_Last_20.txt", row.names = F)
```
